manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: prospector
      url-base: https://github.com/t-ogura
    - name: halfdane
      url-base: https://github.com/halfdane
    - name: ssbb
      url-base: https://github.com/ssbb
    - name: kot149
      url-base: https://github.com/kot149
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: prospector-zmk-module
      remote: prospector
      revision: feature/v2.0-scanner-touch-log-reduction
      path: modules/prospector-zmk-module
    # DISABLED: Mouse gesture modules (not needed for direct touch coordinate logging)
    # - name: zmk-input-processors
    #   remote: halfdane
    #   revision: main
    #   path: modules/zmk-input-processors
    # - name: zmk-input-gestures
    #   remote: halfdane
    #   revision: main
    #   path: modules/zmk-input-gestures
    # - name: zmk-listeners
    #   remote: ssbb
    #   revision: v1
    #   path: modules/zmk-listeners
    # - name: zmk-mouse-gesture
    #   remote: kot149
    #   revision: v1
    #   path: modules/zmk-mouse-gesture
  self:
    path: config